# название
name: Project test & build

# целевые события для запуска
# в данном случае это push и pull_request, в ветку main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# выполняемые действия
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    # запускаются по шагам
    # name - название шага
    # в github actions будет выводиться название шага, и процессы
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          python-version: 3.8.10

      - name: Install 🔧
        run: make install

      - name: Run Test 🔨
        run: make test

      - name: Build 👷
        run: make build
        
